name: Build and Deploy
on: [push]
jobs:
  Create-Environment-Variable:
    runs-on: ubuntu-latest
    env:
      SERVER_PORT: 3000
      API_KEY: ${{ secrets.OCTOKIT_API_SECRET }}
    steps: 
      - run: |
          touch .env
          echo API_KEY="$API_KEY" >> .env
          echo PORT="$SERVER_PORT" >> .env
      
          echo "cat .env"
          cat .env
      
          echo "ls -a ."
          ls -a .
      
          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: echo "Running npm ci"
      - run: npm ci
      - run: echo "Running ls -a"
      - run: ls -a
      - run: echo "Runnnig cd .. then ls -a"
      - run: cd .. ls -a
      - run: npm run dev
